import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const inter = localFont({
    src: "./fonts/InterItalic.ttf",
    variable: "--Inter",
    weight: "400 500 600 700",
});

const interItalic = localFont({
  src: "./fonts/InterItalic.ttf",
  variable: "--InterItalic",
  weight: "400 500 600 700",
});

export const metadata: Metadata = {
  title: "Capybarara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${interItalic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
